[project]
name = "qwen3-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.11"
dependencies = [
    "fastmcp>=2.5.0",
    "pypdf2>=3.0.1",
    "qwen-agent[code-interpreter,gui,mcp]>=0.0.25",
    "reportlab>=4.4.1",
]
